version: '3.8'
services:
  api:
    container_name: api
    build:
      context: .
    environment:
      MONGODB_URL: mongodb://database:27017/urban-nav
      SENDGRID_API_KEY: ""
      SENDGRID_FROM: ""
      TWILIO_SID: ""
      TWILIO_AUTH_TOKEN: ""
      TWILIO_PHONE_NUMBER: ""
      EMAIL_2FA_TEMPLATE_ID: ""
      EMAIL_VERIFICATION_TEMPLATE_ID: ""
      JWT_SECRET: ""
      PASSWORD_RECOVERY_TEMPLATE_ID: ""
      REDIS_HOST: redis
      FRONTEND_URL: "http://localhost:4200"
    ports:
      - 3000:3000
    depends_on:
      - database
      - redis
  database:
    container_name: mongodb
    image: mongo:6
    ports:
      - 27017:27017
  redis:
    container_name: redis
    image: redis:7
    ports:
      - 6379:6379
